{% set data = load_setup_py_data() %}

package:
  name: anaconda-ident
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python  # [not win]
  entry_points:
    - anaconda-ident = anaconda_ident.install:main
    - anaconda-keymgr = anaconda_ident.keymgr:main

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.6
    - conda>=4.11
    - anaconda-anon-usage>=0.4.1,<1

test:
  source_files:
    - tests/test_config.py
    - tests/test_keymgr.sh  # [unix]
    - tests/config_tests.txt  # [unix]
  commands:
    - export ANACONDA_IDENT_DEBUG=1  # [unix]
    - export PYTHONUNBUFFERED=1  # [unix]
    - set ANACONDA_IDENT_DEBUG=1  # [win]
    - set PYTHONUNBUFFERED=1 # [win]
    - conda create -n testchild1 --yes
    - conda create -n testchild2 --yes
    - conda info
    - conda info --envs
    - anaconda-ident --status
    - anaconda-keymgr --help
    - python tests/test_config.py
    - bash tests/test_keymgr.sh  # [unix]

about:
  home: https://github.com/Anaconda-Platform/anaconda-ident
  summary: simple, opt-in user identification for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
