{% set data = load_setup_py_data() %}

package:
  name: anaconda-ident
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  noarch: python
  entry_points:
    - anaconda-ident = anaconda_ident.install:main
    - anaconda-keymgr = anaconda_ident.keymgr:main

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.6
    - conda>=4.11
    - anaconda-anon-usage>=0.4.1,<1

test:
  requires:
    - conda-index
  source_files:
    - tests/
  commands:
    - if [ ! -f $CONDA_PREFIX/etc/conda/activate.d/anaconda-ident_activate.sh ]; then exit 1; fi
    - if [ ! -f $CONDA_PREFIX/etc/conda/activate.d/anaconda-ident_activate.bat ]; then exit 1; fi
    - if [ ! -f $CONDA_PREFIX/bin/.anaconda-ident-pre-unlink.sh ]; then exit 1; fi
    - if [ ! -f $CONDA_PREFIX/bin/.anaconda-ident-pre-unlink.bat ]; then exit 1; fi
    - if [ ! -f $CONDA_PREFIX/bin/.anaconda-ident-post-link.sh ]; then exit 1; fi
    - if [ ! -f $CONDA_PREFIX/bin/.anaconda-ident-post-link.bat ]; then exit 1; fi
    - bash -x tests/run_all_tests.sh

about:
  home: https://github.com/Anaconda-Platform/anaconda-ident
  summary: simple, opt-in user identification for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
