{% set data = load_setup_py_data() %}

package:
  name: conda-ident
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python  # [unix]
  script_env:        
    - CLIENT_TOKEN={{ client_token }}  # [client_token != '']
  string: {{ custom_build | default("custom", true) }}_0  # [custom_build != '' or client_token != '']

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

about:
  home: https://github.com/mcg1969/conda-ident
  summary: simple, opt-in user identification for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
