{% set data = load_setup_py_data() %}

package:
  name: conda-ident
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python  # [unix]
  script_env:
    - CONFIG_STRING={{ config_string }}  # [config_string != "blank"]
    - CONFIG_STRING=  # [config_string == "blank"]
    - DEFAULT_CHANNELS={{ default_channels }}  # [default_channels != "blank"]
    - DEFAULT_CHANNELS=  # [default_channels == "blank"]
    - CHANNEL_ALIAS={{ channel_alias }}  # [channel_alias != "blank"]
    - CHANNEL_ALIAS=  # [channel_alias == "blank"]
    - REPO_TOKEN={{ repo_token }}  # [repo_token != "blank"]
    - REPO_TOKEN=  # [repo_token == "blank"]
  string: {{ custom_build | default("custom", true) }}_0  # [custom_build or config_string]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

about:
  home: https://github.com/mcg1969/conda-ident
  summary: simple, opt-in user identification for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
