{% set data = load_setup_py_data() %}

package:
  name: anaconda-ident
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  noarch: python
  entry_points:
    - anaconda-ident = anaconda_ident.install:main
    - anaconda-keymgr = anaconda_ident.keymgr:main
    - anaconda-heartbeat = anaconda_ident.heartbeat:main
    - anaconda-ident-hash = anaconda_ident.tokens:main

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.6
    - conda>=23.7.1
    - anaconda-anon-usage>=0.5,<1
  run_constrained:
    - anaconda_client >=1.12.2

test:
  requires:
    - conda-index
  source_files:
    - tests/
  commands:
    - if not exist %CONDA_PREFIX%\\etc\\conda\\activate.d\\anaconda-ident_activate.bat exit 1  # [win]
    - if not exist %CONDA_PREFIX%\\Scripts\\.anaconda-ident-pre-unlink.bat exit 1  # [win]
    - if not exist %CONDA_PREFIX%\\Scripts\\.anaconda-ident-post-link.bat exit 1  # [win]
    - if [ ! -f $CONDA_PREFIX/etc/conda/activate.d/anaconda-ident_activate.sh ]; then exit 1; fi  # [unix]
    - if [ ! -f $CONDA_PREFIX/bin/.anaconda-ident-pre-unlink.sh ]; then exit 1; fi  # [unix]
    - if [ ! -f $CONDA_PREFIX/bin/.anaconda-ident-post-link.sh ]; then exit 1; fi  # [unix]
    - export ANACONDA_IDENT_DEBUG=1  # [unix]
    - export PYTHONUNBUFFERED=1  # [unix]
    - set ANACONDA_IDENT_DEBUG=1  # [win]
    - set PYTHONUNBUFFERED=1  # [win]
    - anaconda-ident --expect
    - conda create -n testchild1 --yes
    - conda create -n testchild2 --yes
    - conda info
    - conda info --envs
    - anaconda-keymgr --help
    - anaconda-ident-hash --help
    - python tests/test_config.py
    - export ANACONDA_IDENT=full:testorg  # [unix]
    - set ANACONDA_IDENT=full:testorg # [win]
    - python tests/test_heartbeats.py

about:
  home: https://github.com/Anaconda-Platform/anaconda-ident
  summary: simple, opt-in user identification for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
