{% set data = load_setup_py_data() %}

package:
  name: anaconda-ident
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  entry_points:
    - anaconda-ident = anaconda_ident.install:main
    - anaconda-keymgr = anaconda_ident.keymgr:main

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.6
    - conda>=22.11.0

test:
  commands:
    - anaconda-ident --status
    - anaconda-keymgr --help

about:
  home: https://github.com/Anaconda-Platform/anaconda-ident
  summary: simple, opt-in user identification for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
