{% set data = load_setup_py_data() %}

package:
  name: conda-ident
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python  # [unix]
  script_env:
    - CONFIG_STRING={{ config_string }}  # [config_string != '']
    - DEFAULT_CHANNELS={{ default_channels }}  # [default_channels != '']
    - CHANNEL_ALIAS={{ channel_alias }}  # [channel_alias != '']
    - REPO_TOKEN={{ repo_token }}  # [repo_token != '' ]
  string: {{ custom_build | default("custom", true) }}_0  # [custom_build != '' or config_string != '' or repo_token != '' or default_channels != '' or channel_alias != '']

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

about:
  home: https://github.com/mcg1969/conda-ident
  summary: simple, opt-in user identification for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
