name: Custom Builds
on:
  workflow_dispatch:
    inputs:
      build_string:
        description: 'Build string'
        default: 'custom'
        required: true
      config_string:
        description: 'Client token configuration string'
        default: 'default'
        required: true
      default_channels:
        description: 'Comma-separated list of default_channels values'
        default: ''
        required: false
      channel_alias:
        description: 'Channel alias'
        default: ''
        required: false
      repo_token:
        description: 'Repository token'
        default: ''
        required: false
jobs:
  package:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      with:
        fetch-depth: 0        
    - name: Install the build environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install conda-build anaconda-client
    - name: Build the package
      if: github.event_name == 'workflow_dispatch'
      run: |
        source $CONDA/etc/profile.d/conda.sh
        str=${{ github.event.inputs.build_string }}
        cfg=${{ github.event.inputs.config_string }}
        def=${{ github.event.inputs.default_channels }}
        cal=${{ github.event.inputs.channel_alias }}
        rtk=${{ github.event.inputs.repo_token }}
        variant='{"custom_build":"'$str'","config_string":"'$cfg'","default_channels":"'$def'","channel_alias":"'$cal'","repo_token":"'$rtk'"}'
        conda build conda.recipe --variants "$variant"
    - name: Upload to anaconda.org
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate base
        [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || export LABEL="--label dev"
        anaconda --verbose --token $ANACONDA_TOKEN upload --user mcg $LABEL $CONDA/conda-bld/*/*.tar.bz2 --force
