name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  package:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      with:
        fetch-depth: 0        
    - name: Install the build environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install conda-build anaconda-client
    - name: Build the package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda build conda.recipe
    - name: Run multiple token tests
      run: |
        mkdir -p $CONDA/build2
        source $CONDA/etc/profile.d/conda.sh
        conda config --prepend channels local
        conda build token.recipe -m custom_builds.yaml --croot $CONDA/build2
    - name: Upload to anaconda.org
      if: github.event_name == 'push'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate base
        [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || export LABEL="--label dev"
        anaconda --verbose --token $ANACONDA_TOKEN upload --user mcg $LABEL $CONDA/conda-bld/*/*.tar.bz2 --force
