name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

concurrency:
  # Concurrency group that uses the workflow name and PR number if available
  # or commit SHA as a fallback. If a new build is triggered under that
  # concurrency group while a previous build is running it will be canceled.
  # Repeated pushes to a PR will cancel all previous builds, while multiple
  # merges to main will not cancel.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
    - name: Build the package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate base
        conda install conda conda-build conda-index
        conda build conda.recipe --no-test
        aid_version=$(conda search local::anaconda-ident | grep ^anaconda-ident | awk '{print $2}' | tail -1)
        conda install -c local anaconda-ident=$aid_version
        bash tests/test_keymgr.sh --build-only
        mv $CONDA/conda-bld .
    - name: Upload build artifacts
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
      with:
        if-no-files-found: error
        name: conda-bld
        path: conda-bld/
  # This is just to test that the windows build process works. We do not
  # actually use this artifact.
  build-win:
    runs-on: windows-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        fetch-depth: 0
    - name: Build the package
      shell: bash
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate base
        conda install conda conda-build
        conda build conda.recipe
  tests:
    needs: build
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cversion: ['23.7.4', '23.9.0', '23.10.0', '23.11.0', '24.1.2', '24.3.0']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Download build artfiacts
      uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d # v4
      with:
        name: conda-bld
        path: ./conda-bld
    - name: Run local tests
      run: |
        mv conda-bld $CONDA/
        source $CONDA/etc/profile.d/conda.sh
        aid_version=$(conda search local::anaconda-ident | awk '{print $2}' | tail -1)
        conda create -p ./testenv -c local anaconda-ident=$aid_version conda=${{ matrix.cversion }}
        source ./testenv/etc/profile.d/conda.sh
        conda activate base
        conda create -n testchild1 --yes
        conda create -n testchild2 --yes
        python tests/test_config.py
        python tests/test_heartbeats.py
    - name: Build the test environment and an installer
      env:
        TEST_REPO_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install constructor conda-index
        aid_version=$(conda search local::anaconda-ident | grep ^anaconda-ident | awk '{print $2}' | tail -1)
        CONDA_PREFIX=$CONDA bash tests/test_installer.sh $TEST_REPO_TOKEN $aid_version ${{ matrix.cversion }}
    - name: Run the installer (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: start /wait AIDTest-1.0-Windows-x86_64.exe /S /D=%USERPROFILE%\aidtest
    - name: Run the installer (Unix)
      if: matrix.os != 'windows-latest'
      run: bash AIDTest*.sh -b -p ~/aidtest -k
    - name: Test the installed environment
      env:
        TEST_REPO_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        ANACONDA_IDENT_DEBUG: "1"
        ANACONDA_IDENT_RAISE: "1"
      run: bash tests/test_environment.sh ~/aidtest "$TEST_REPO_TOKEN"
  upload:
    needs: [tests, build-win]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d # v4
      with:
        name: conda-bld
        path: ./conda-bld
    - name: Upload to anaconda.org
      if: github.event_name == 'push'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        source $CONDA/bin/activate
        conda install anaconda-client
        [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || export LABEL="--label dev"
        # Remove the macos build, use the unix noarch instead
        rm -rf conda-bld/osx-64 || :
        anaconda --verbose --token $ANACONDA_TOKEN upload --user mcg $LABEL conda-bld/*/*.tar.bz2 --force
