name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      with:
        fetch-depth: 0        
    - name: Install the build environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install conda-build
    - name: Build the package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda build conda.recipe --no-test
        mv $CONDA/conda-bld .
    - name: Upload build artifacts
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
      with:
        if-no-files-found: error
        name: conda-bld
        path: conda-bld/
  test:
    needs: build
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        cversion: [22.11.0,23.5.0]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      with:
        fetch-depth: 0        
    - name: Download build artfiacts
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
      with:
        name: conda-bld
        path: ./conda-bld
    - name: Build test environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        mv conda-bld $CONDA/
        conda create -p ./testenv local::anaconda-ident conda==${{ matrix.cversion }}
    - name: Test the package
      run: |
        set -x
        source ./testenv/*/activate
        cd tests
        python -m anaconda_ident.install --status
        python test_config.py
        bash test_keymgr.sh
  upload:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Download package
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
      with:
        name: conda-bld
        path: ./conda-bld
    - name: Upload to anaconda.org
      if: github.event_name == 'push'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        source $CONDA/bin/activate
        conda install anaconda-client
        [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || export LABEL="--label dev"
        anaconda --verbose --token $ANACONDA_TOKEN upload --user mcg $LABEL conda-bld/*/*.tar.bz2 --force
