name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      with:
        fetch-depth: 0        
    - name: Install the build environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install conda-build
    - name: Build the package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda build conda.recipe --no-test
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        path:
          - $CONDA/conda-bld
  test:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Retrieve the source code
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3
      with:
        fetch-depth: 0        
    - name: Install the build environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install conda-build
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        path:
          - $CONDA/conda-bld
    - name: Test the package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda build --test $CONDA/conda-bld/noarch/*.tar.bz2
  upload:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - name: Install the upload environment
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda install anaconda-client
    - name: Download package
      uses: actions/download-artifact@v3
      with:
        path:
          - $CONDA/conda-bld
    - name: Test the package
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda build --test $CONDA/conda-bld/noarch/*.tar.bz2
    - name: Upload to anaconda.org
      if: github.event_name == 'push'
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate base
        [[ "$GITHUB_REF" =~ ^refs/tags/ ]] || export LABEL="--label dev"
        anaconda --verbose --token $ANACONDA_TOKEN upload --user mcg $LABEL $CONDA/conda-bld/*/*.tar.bz2 --force
